// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('WEB_API_KEY'),
    appId: String.fromEnvironment('WEB_APP_ID'),
    messagingSenderId: '786206108520',
    projectId: 'chat-app-af4eb',
    authDomain: 'chat-app-af4eb.firebaseapp.com',
    storageBucket: 'chat-app-af4eb.firebasestorage.app',
    measurementId: 'G-0EWEGEP2XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('ANDROID_API_KEY'),
    appId: String.fromEnvironment('ANDROID_APP_ID'),
    messagingSenderId: '786206108520',
    projectId: 'chat-app-af4eb',
    storageBucket: 'chat-app-af4eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('IOS_API_KEY'),
    appId: String.fromEnvironment('IOS_APP_ID'),
    messagingSenderId: '786206108520',
    projectId: 'chat-app-af4eb',
    storageBucket: 'chat-app-af4eb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('MACOS_API_KEY'),
    appId: String.fromEnvironment('MACOS_APP_ID'),
    messagingSenderId: '786206108520',
    projectId: 'chat-app-af4eb',
    storageBucket: 'chat-app-af4eb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('WINDOWS_API_KEY'),
    appId: String.fromEnvironment('WINDOWS_APP_ID'),
    messagingSenderId: '786206108520',
    projectId: 'chat-app-af4eb',
    authDomain: 'chat-app-af4eb.firebaseapp.com',
    storageBucket: 'chat-app-af4eb.firebasestorage.app',
    measurementId: 'G-SHDYNKNSSQ',
  );
}
