// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1yQvJP2UujXCdfjpmb0YjS315ONIchjQ',
    appId: '1:786206108520:web:452e41e54fd0340f4bc4dd',
    messagingSenderId: '786206108520',
    projectId: 'chat-app-af4eb',
    authDomain: 'chat-app-af4eb.firebaseapp.com',
    storageBucket: 'chat-app-af4eb.firebasestorage.app',
    measurementId: 'G-0EWEGEP2XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmn2qtjalzIxMrGLjLgTTXP784t1_JMgM',
    appId: '1:786206108520:android:23f60675614a17194bc4dd',
    messagingSenderId: '786206108520',
    projectId: 'chat-app-af4eb',
    storageBucket: 'chat-app-af4eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxzOjAd0QyMGuEDgyof_ljrgwDBiUnmIU',
    appId: '1:786206108520:ios:4ad90d7dfc0e976a4bc4dd',
    messagingSenderId: '786206108520',
    projectId: 'chat-app-af4eb',
    storageBucket: 'chat-app-af4eb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxzOjAd0QyMGuEDgyof_ljrgwDBiUnmIU',
    appId: '1:786206108520:ios:4ad90d7dfc0e976a4bc4dd',
    messagingSenderId: '786206108520',
    projectId: 'chat-app-af4eb',
    storageBucket: 'chat-app-af4eb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1yQvJP2UujXCdfjpmb0YjS315ONIchjQ',
    appId: '1:786206108520:web:c378071ffcceb64c4bc4dd',
    messagingSenderId: '786206108520',
    projectId: 'chat-app-af4eb',
    authDomain: 'chat-app-af4eb.firebaseapp.com',
    storageBucket: 'chat-app-af4eb.firebasestorage.app',
    measurementId: 'G-SHDYNKNSSQ',
  );
}
